/**
 * ResponseBubbles.tsx
 * v35.0 - Dynamic response suggestion bubbles
 *
 * Renders clickable suggestion bubbles below agent messages
 * to enable faster student responses (60min → 15-20min assessments)
 *
 * Features:
 * - Smooth Apple-grade animations (slide-in, click, fade-out)
 * - 3-4 contextual suggestions per question
 * - Auto-hides after user clicks or starts typing
 * - Graceful degradation if no suggestions available
 *
 * Integration:
 * - Used by MultiAgentsTabRedesigned for assessment flow
 * - Receives suggestions from backend (LLM-generated via DynamicQuestionGenerator)
 * - onClick sends selected response back to chat
 *
 * @file src/components/v26/ResponseBubbles.tsx
 */

import React, { useState, useEffect } from 'react';
import styled, { keyframes } from 'styled-components';

// ============================================
// INTERFACES
// ============================================

export interface ResponseBubblesProps {
  /** Array of 3-4 suggested response options */
  suggestions: string[];
  /** Callback when user clicks a bubble */
  onBubbleClick: (response: string) => void;
  /** Controls visibility (auto-hide when user starts typing) */
  isVisible: boolean;
  /** Optional: Message ID for tracking which message these bubbles belong to */
  messageId?: string;
}

// ============================================
// ANIMATIONS
// ============================================

const slideIn = keyframes`
  from {
    opacity: 0;
    transform: translateY(10px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
`;

const fadeOut = keyframes`
  from {
    opacity: 1;
    transform: scale(1);
  }
  to {
    opacity: 0;
    transform: scale(0.95);
  }
`;

const bubbleClick = keyframes`
  0% {
    transform: scale(1);
  }
  50% {
    transform: scale(0.95);
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  }
  100% {
    transform: scale(1);
    opacity: 0;
  }
`;

// ============================================
// STYLED COMPONENTS
// ============================================

const BubblesContainer = styled.div<{ isVisible: boolean; isHiding: boolean }>`
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-top: 12px;
  padding: 0 16px;
  animation: ${props =>
    props.isHiding
      ? fadeOut
      : props.isVisible
        ? slideIn
        : 'none'
  } 0.3s ease-in-out;
  opacity: ${props => props.isVisible && !props.isHiding ? 1 : 0};
  pointer-events: ${props => props.isVisible && !props.isHiding ? 'auto' : 'none'};
  transition: opacity 0.3s ease-in-out;
`;

const Bubble = styled.button<{ isClicked: boolean }>`
  padding: 10px 16px;
  background: ${props =>
    props.isClicked
      ? 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)'
      : 'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)'
  };
  color: ${props => props.isClicked ? '#ffffff' : '#2d3748'};
  border: none;
  border-radius: 20px;
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  transition: all 0.2s ease-in-out;
  animation: ${props => props.isClicked ? bubbleClick : 'none'} 0.3s ease-in-out;
  white-space: nowrap;
  max-width: 250px;
  overflow: hidden;
  text-overflow: ellipsis;

  &:hover:not(:disabled) {
    transform: translateY(-2px);
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.15);
    background: linear-gradient(135deg, #e3e8f0 0%, #b8c6db 100%);
  }

  &:active:not(:disabled) {
    transform: translateY(0);
    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);
  }

  &:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  @media (max-width: 768px) {
    font-size: 13px;
    padding: 8px 14px;
    max-width: 200px;
  }
`;

const BubbleIcon = styled.span`
  margin-right: 6px;
  font-size: 12px;
`;

const HintText = styled.div`
  font-size: 12px;
  color: #718096;
  margin-top: 8px;
  padding: 0 16px;
  font-style: italic;
  animation: ${slideIn} 0.4s ease-in-out 0.2s both;
`;

// ============================================
// COMPONENT
// ============================================

/**
 * ResponseBubbles
 *
 * Renders clickable suggestion bubbles that help students respond faster
 * during assessments. Suggestions are generated by LLM (GPT-4o-mini) based
 * on context, student profile, and conversation history.
 *
 * Usage:
 * ```tsx
 * <ResponseBubbles
 *   suggestions={["Yes, definitely", "Not really", "I'm not sure yet"]}
 *   onBubbleClick={(response) => handleSendMessage(response)}
 *   isVisible={true}
 * />
 * ```
 */
export const ResponseBubbles: React.FC<ResponseBubblesProps> = ({
  suggestions,
  onBubbleClick,
  isVisible,
  messageId
}) => {
  const [clickedBubble, setClickedBubble] = useState<string | null>(null);
  const [isHiding, setIsHiding] = useState(false);

  // Reset clicked state when visibility changes
  useEffect(() => {
    if (!isVisible) {
      setClickedBubble(null);
      setIsHiding(false);
    }
  }, [isVisible]);

  // Handle bubble click with animation
  const handleClick = (suggestion: string) => {
    if (clickedBubble) return; // Prevent double-click

    setClickedBubble(suggestion);

    // Trigger fade-out animation
    setTimeout(() => {
      setIsHiding(true);
    }, 100);

    // Call parent callback after animation completes
    setTimeout(() => {
      onBubbleClick(suggestion);
      setClickedBubble(null);
      setIsHiding(false);
    }, 400);
  };

  // Don't render if no suggestions
  if (!suggestions || suggestions.length === 0) {
    return null;
  }

  return (
    <>
      <BubblesContainer
        isVisible={isVisible}
        isHiding={isHiding}
        data-message-id={messageId}
      >
        {suggestions.map((suggestion, index) => (
          <Bubble
            key={`bubble-${messageId}-${index}`}
            onClick={() => handleClick(suggestion)}
            disabled={clickedBubble !== null}
            isClicked={clickedBubble === suggestion}
            title={suggestion} // Show full text on hover if truncated
          >
            <BubbleIcon>💬</BubbleIcon>
            {suggestion}
          </Bubble>
        ))}
      </BubblesContainer>

      {isVisible && !isHiding && suggestions.length > 0 && (
        <HintText>
          ✨ Quick responses or type your own
        </HintText>
      )}
    </>
  );
};

export default ResponseBubbles;

/**
 * USAGE EXAMPLE:
 *
 * import { ResponseBubbles } from './ResponseBubbles';
 *
 * function ChatWindow() {
 *   const [bubblesSuggestions, setBubblesSuggestions] = useState<string[]>([]);
 *   const [showBubbles, setShowBubbles] = useState(false);
 *
 *   // When agent sends message with suggestions
 *   useEffect(() => {
 *     if (latestMessage.suggested_responses?.length > 0) {
 *       setBubblesSuggestions(latestMessage.suggested_responses);
 *       setShowBubbles(true);
 *     }
 *   }, [latestMessage]);
 *
 *   // When user starts typing, hide bubbles
 *   const handleInputChange = (value: string) => {
 *     if (value.length > 0) {
 *       setShowBubbles(false);
 *     }
 *   };
 *
 *   const handleBubbleClick = (response: string) => {
 *     sendMessage(response);
 *     setShowBubbles(false);
 *   };
 *
 *   return (
 *     <div>
 *       {messages.map(msg => (
 *         <div key={msg.id}>
 *           <MessageBubble message={msg} />
 *           {msg.role === 'agent' && msg.suggested_responses && (
 *             <ResponseBubbles
 *               suggestions={msg.suggested_responses}
 *               onBubbleClick={handleBubbleClick}
 *               isVisible={showBubbles}
 *               messageId={msg.id}
 *             />
 *           )}
 *         </div>
 *       ))}
 *       <input onChange={(e) => handleInputChange(e.target.value)} />
 *     </div>
 *   );
 * }
 */
